---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hyperland-ewt
# description will be included in the image's metadata
description: Personal Hyprland-based OS image with efficient tiling window management.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - solopasha/hyprland  # Primary Hyprland packages
        - atim/starship       # Shell prompt
        - aquacash5/nerd-fonts # Nerd Fonts collection
    install:
      packages:
        # Core Hyprland ecosystem
        - hyprland
        - xdg-desktop-portal-hyprland
        - hyprland-contrib
        - hyprpaper
        - hyprpicker
        
        # Essential Wayland ecosystem
        - waybar              # Status bar
        - rofi-wayland        # Application launcher
        - kitty               # Terminal emulator
        - dunst               # Notifications
        - thunar              # File manager
        - qt5-qtwayland       # Qt5 Wayland support
        - qt6-qtwayland       # Qt6 Wayland support
        
        # System utilities
        - brightnessctl       # Brightness control
        - fastfetch           # System info
        - jq                  # JSON processor
        - grim                # Screenshot utility
        - slurp               # Screen area selection
        - wl-clipboard        # Wayland clipboard
        - swaylock            # Screen locker
        - wlogout             # Logout menu
        
        # Keep existing tools
        - micro
        - starship
        - oh-my-posh
        - tmux
        
        # Fonts
        - fontconfig
        - hack-nerd-fonts
        
        # Development tools for Homebrew support
        - curl
        - git
        - gcc
        - gcc-c++
        - make
        - procps-ng
        
        # Code editors and development environment
        - nodejs                  # Required for Claude Code CLI
        - npm                     # Package manager for Claude Code
        
        # Container and virtualization tools
        - podman                  # Container management
        - podman-compose          # Docker-compose compatibility
        - libvirt                 # Virtualization API
        - libvirt-daemon-config-network  # Default network for libvirt
        - libvirt-daemon-kvm      # KVM hypervisor daemon
        - qemu-kvm                # QEMU virtualization
        - virt-manager            # GUI for managing VMs
        - virt-install            # Command line VM installation
        - virt-viewer             # VM display viewer
        
        # Kubernetes tools
        - k3s                     # Lightweight Kubernetes
        - kubernetes-client       # kubectl command
        - helm                    # Kubernetes package manager
        
        # Hardware and firmware tools
        - qmk                     # QMK keyboard firmware
        - arduino                 # Arduino IDE
        
        # Network diagnostic tools
        - bind-utils              # nslookup, dig, host
        - nmap                    # Network mapper
        - nmap-ncat               # nc (netcat) replacement
        - iputils                 # ping, traceroute
        - iproute                 # ip command
        - tcpdump                 # Packet analyzer
        - wireshark               # Network protocol analyzer
        - mtr                     # Network diagnostic tool (ping + traceroute)
        
        # System monitoring and resource tools
        - htop                    # Interactive process viewer
        - btop                    # Modern resource monitor
        - iotop                   # I/O monitor
        - iftop                   # Network bandwidth monitor
        - nethogs                 # Per-process network monitor
        - sysstat                 # Performance monitoring (sar, iostat, mpstat)
        - lsof                    # List open files
        - strace                  # System call tracer
        
        # USB and hardware tools
        - usbutils                # lsusb, usb-devices
        - pciutils                # lspci
        - hwinfo                  # Hardware information
        - lshw                    # Hardware lister
        
        # File and directory browsing
        - tree                    # Directory tree viewer
        - ranger                  # TUI file manager
        - mc                      # Midnight Commander
        - fzf                     # Fuzzy finder
        - ripgrep                 # Fast grep alternative
        - fd-find                 # Fast find alternative
        - bat                     # Cat with syntax highlighting
        
        # TUI applications (eza, lazygit, lazydocker, dive, ctop, systemctl-tui installed via setup-tui-tools.sh)
        - podman-tui              # Podman TUI
        - ncdu                    # Disk usage analyzer
    remove:
      packages:
        # Remove GNOME components that conflict with Hyprland
        - firefox
        - firefox-langpacks
        - gnome-shell-extension-apps-menu
        - gnome-shell-extension-launch-new-instance
        - gnome-shell-extension-places-menu
        - gnome-shell-extension-window-list

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
          - com.github.tchx84.Flatseal  # Flatpak permissions manager
          - io.freetubeapp.FreeTube
          - dev.zed.Zed                  # Zed code editor
          - io.github.zen_browser.zen    # Zen browser
          - io.k9s.k9s                   # Kubernetes TUI
      - scope: user # Also add Flathub user repo, but no user packages

  - type: script
    scripts:
      - hypr-post-install.sh  # Post-installation Hyprland setup

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
